

main:
  - name: Home
    url: #about
    weight: 10
  - name: Writing
    url: post
    weight: 20
  - name: Running
    url: running
    weight: 30
  - name: Publications
    url: publications
    weight: 40
  - name: Media
    url: media
    weight: 50
  - name: CV
    url: /uploads/cv_cornell.pdf
    weight: 60

 