# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: #about
    weight: 10
  - name: Writing
    url: post
    weight: 20
  - name: Running
    url: running
    weight: 30
  - name: Publications
    url: publications
    weight: 40
  - name: CV
    url: media/cv_cornell.pdf
    weight: 50

 