

main:
  - name: Home
    url: #about
    weight: 10
  - name: Writing
    url: post
    weight: 20
  - name: Blog
    url: https://samcornell.substack.com/
    weight: 30
  - name: Publications
    url: publications
    weight: 40
  - name: Media
    url: media
    weight: 50
  - name: Academic CV
    url: /uploads/cv_cornell.pdf
    weight: 60
  - name: Resume
    url: /uploads/resume_cornell.pdf
    weight: 70